#!/usr/bin/env nextflow
nextflow.enable.dsl = 2

// Perform FLARE (last tested on v0.5.3)
process RUN_FLARE {
    // debug true
    label 'flare'
    // conda '/storage/atkinson/home/u235158/anaconda3/envs/sambam'
    tag {chr}

    publishDir "${params.outdir}/3_lai", pattern: '*.{anc.vcf.gz}', failOnError: true, overwrite: true
    publishDir "${params.outdir}/3_lai", pattern: '*.log', mode: 'copy', failOnError: true, overwrite: true
    publishDir "${params.outdir}/3_lai", pattern: '*.{model}', failOnError: true, overwrite: true

    input:
    val output_prefix
    tuple val(chr),path(vcf),path(vcf_idx)
    tuple path(ref_vcf),path(ref_vcf_idx)
    path flare_dir
    path sample_map
    path flare_genetic_map
    val is_array
    val min_maf
    val min_mac
    val probs
    val gen
    val flare_model
    val em
    val gt_samples_include
    val gt_samples_exclude
    val gt_ancestries
    val excludemarkers
    val seed

    output:
    path "${output_prefix}_${chr}.log"                  , emit: flare_log   // log file generated by FLARE itself
    path "${output_prefix}_${chr}.flare.log"            , emit: log         // stdout+err of the Nextflow run
    path "${output_prefix}_${chr}.model"                , emit: model
    tuple val(chr),
          path("${output_prefix}_${chr}.anc.vcf.gz")    , emit: anc_vcf


    script:
    
    def args   = task.ext.args   ?: ''
    // Optional args
    def min_maf_cmd          = min_maf             ? "min-maf=${min_maf}"                   : ""
    def min_mac_cmd          = min_mac             ? "min-mac=${min_mac}"                   : ""
    def gen_cmd              = gen                 ? "gen=${gen}"                           : ""
    def flare_model_cmd      = flare_model         ? "model=${flare_model}"                 : ""
    def gt_samples_incl_cmd  = gt_samples_include  ? "gt-samples=${gt_samples_include}"     : ""
    def gt_samples_excl_cmd  = gt_samples_exclude  ? "gt-samples=^${gt_samples_exclude}"    : ""
    def gt_ancestries_cmd    = gt_ancestries       ? "gt-ancestries=${gt_ancestries}"       : ""
    def excludemarkers_cmd   = excludemarkers      ? "excludemarkers=${excludemarkers}"     : ""
    def seed_cmd             = seed                ? "seed=${seed}"                         : ""
    
    // allowing both true/false values. The aforemention approach only allows non "false" values
    def is_array_cmd         = "array=${is_array}"
    def probs_cmd            = "probs=${probs}"
    def em_cmd               = "em=${em}"

    // define memory
    def memG = task.memory.toGiga() as int
    def memXmx = memG > 2 ? (memG * 0.85) as int : memG   // Take 85% of memory provide to allow for overhead (only if memory > 2Gb)
    """
    java -Xmx${memXmx}g -jar ${flare_dir}/flare.jar \\
    ref=${ref_vcf} \\
    ref-panel=${sample_map} \\
    gt=${vcf} \\
    map=${flare_genetic_map} \\
    out=${output_prefix}_${chr} \\
    nthreads=${task.cpus} \\
    $is_array_cmd \\
    $min_maf_cmd \\
    $min_mac_cmd \\
    $probs_cmd \\
    $gen_cmd \\
    $flare_model_cmd \\
    $em_cmd \\
    $gt_samples_incl_cmd \\
    $gt_samples_excl_cmd \\
    $gt_ancestries_cmd \\
    $excludemarkers_cmd \\
    $seed_cmd

    cp .command.log ${output_prefix}_${chr}.flare.log
    """

    stub:
    // Optional args
    def min_maf_cmd          = min_maf             ? "min-maf=${min_maf}"                   : ""
    def min_mac_cmd          = min_mac             ? "min-mac=${min_mac}"                   : ""
    def gen_cmd              = gen                 ? "gen=${gen}"                           : ""
    def flare_model_cmd      = flare_model         ? "model=${flare_model}"                 : ""
    def gt_samples_incl_cmd  = gt_samples_include  ? "gt-samples=${gt_samples_include}"     : ""
    def gt_samples_excl_cmd  = gt_samples_exclude  ? "gt-samples=^${gt_samples_exclude}"    : ""
    def gt_ancestries_cmd    = gt_ancestries       ? "gt-ancestries=${gt_ancestries}"       : ""
    def excludemarkers_cmd   = excludemarkers      ? "excludemarkers=${excludemarkers}"     : ""
    def seed_cmd             = seed                ? "seed=${seed}"                         : ""
    
    // allowing both true/false values. The aforemention approach only allows non "false" values
    def is_array_cmd         = "array=${is_array}"
    def probs_cmd            = "probs=${probs}"
    def em_cmd               = "em=${em}"

    // define memory
    def memG = task.memory.toGiga() as int
    def memXmx = memG > 2 ? (memG * 0.85) as int : memG   // Take 85% of memory provide to allow for overhead (only if memory > 2Gb)

    """
    echo "java -Xmx${memXmx}g -jar ${flare_dir}/flare.jar \\
    ref=${ref_vcf} \\
    ref-panel=${sample_map} \\
    gt=${vcf} \\
    map=${flare_genetic_map} \\
    out=${output_prefix}_${chr} \\
    nthreads=${task.cpus} \\
    $is_array_cmd \\
    $min_maf_cmd \\
    $min_mac_cmd \\
    $probs_cmd \\
    $gen_cmd \\
    $flare_model_cmd \\
    $em_cmd \\
    $gt_samples_incl_cmd \\
    $gt_samples_excl_cmd \\
    $gt_ancestries_cmd \\
    $excludemarkers_cmd \\
    $seed_cmd

    cp .command.log ${output_prefix}_${chr}.flare.log"

    touch ${output_prefix}_${chr}.flare.log
    touch ${output_prefix}_${chr}.log
    touch ${output_prefix}_${chr}.model
    touch ${output_prefix}_${chr}.anc.vcf.gz
    """

}

// Note: 
// FLARE generates output VCF file with ancestry calls, but the output VCF file is not indexed.
// So, input to next step (extract_tracts_flare) cannot include FLARE output VCF's index file.

// Option 1 to control for memory: MEM_GB=$(echo "${task.memory.toGiga()} * 0.8" | bc | awk '{print int($1)}')
// Option 2 (in Groovy):
// script:
//    def mem80 = (task.memory.toGiga() * 0.8) as int


// process RUN_FLARE {
//     label 'run_flare'
//     tag "$input_id"

//     publishDir "${params.outdir}/flare", mode: 'copy', overwrite: true

//     input:
//     val input_id
//     val mem_gb                   // e.g. 16
//     path flare_jar              // the flare.jar file
//     path required_input         // e.g. a data file
//     val required_arg            // a required CLI argument
//     val optional_arg1           // optional flag or value (can be empty)
//     val optional_arg2

//     output:
//     path "${input_id}.*", optional: true, emit: results

//     script:
//     def opt1 = optional_arg1 ? "--opt1 ${optional_arg1}" : ""
//     def opt2 = optional_arg2 ? "--opt2 ${optional_arg2}" : ""

//     """
//     java -Xmx${mem_gb}g -jar ${flare_jar} \\
//         --input ${required_input} \\
//         --required ${required_arg} \\
//         ${opt1} \\
//         ${opt2} \\
//         --output ${input_id}.flare.out
//     """
// }


// // In the config file
// process {
//     withName: RUN_FLARE {
//         memory = { mem_gb -> "${mem_gb} GB" }
//     }
// }


